### ISSUE TITLE
Bad encoding output  in print results

### ISSUE THREAD

**Issue by Insolita** [JetBrains/qodana-action#2]
Some symbols like "<", ">" showed as unicode
![2020-12-15_01-48](https://user-images.githubusercontent.com/1847402/102116587-256f9780-3e78-11eb-8091-1584ab26fdd1.png)

**Comment by a-kuznetsova** [comment]
Hi @Insolita,

Thank you for reporting the issue! I have created a [ticket](https://youtrack.jetbrains.com/issue/QD-636) in out YouTrack.

**Comment by a-kuznetsova** [comment]
Hi @Insolita,

the issue was fixed in the 2021.1-eap version (or qodana-action v2.0).
