### ISSUE TITLE
Long duration

### ISSUE THREAD

**Issue by patricksan** [JetBrains/qodana-action#5]
I just tried the Qodana-action and it took 11m23s in a very small hello world project I have.

<img width="1197" alt="Screen Shot 2021-02-11 at 14 15 56" src="https://user-images.githubusercontent.com/81615/107641898-78957900-6c74-11eb-9051-e391220dfc48.png">

Is it something you guys are aware of it?

Thank you

**Comment by avafanasiev** [comment]
Hi! Sure, it's one of our most important targets - reducing build time.

**Comment by patricksan** [comment]
Thanks @avafanasiev .
Closes #5
